Gwion/Gwion

- Makefile
- src/instr.c
- src/type.c
These are a few of the fixes I had to do to get your project to build up until I hit the libsoundio dependency. Mostly they are Makefile tweaks and fixes for C99 C. 
I'm hoping to keep this PR open until I can actually build Gwion on my machine.
> Build fixes

- Makefile
- ast/gwion.y
- config.mk
I had to mess with the YACC file some more.
Also, I changed the Makefile so the target was all lowercase. In the Unix world, programs are always lowercase. 
I also added the gwion binary to the "clean" target in the Makefile. You typically want to do that...
> Build fixes to get things to compile

- driver/jack.c
This function was giving me an error. I think I fixed it, but I was mostly guessing?
Anyways, I get sound now so that's good!
> JACK shutdown fix

- drvr/jack.c
- drvr/portaudio.c
- include/driver.h
Awesome project. 
Added fixes to compile portaudio and jack.
> Add fixes compile portaudio and jack

- include/absyn.h
- src/ast/absyn.c
- src/ast/parser.c
- src/emit/emit.c
- src/instr.c
- src/lib/float.c
- src/lib/import.c
- src/lib/modules.c
- src/lib/ugen.c
- src/lib/vec.c
- src/oo/vm.c
- src/parse/check.c
- src/parse/operator.c
- src/parse/scan.c
- src/util/utils.c
- tests/error/invalid_for.gw
- tests/error/invalid_until.gw
- tests/error/invalid_while.gw
- utils/gwion.y
> :art: emit.c end

- include/driver.h
- src/drvr/alsa.c
- src/drvr/dummy.c
- src/drvr/jack.c
- src/drvr/portaudio.c
- src/drvr/sndfile.c
- src/drvr/soundio.c
- src/drvr/spa.c
- src/main.c
> :art: DriverInfo->run

- configure
- include/driver.h
- src/drvr/driver.c
- src/drvr/pulse.c
- utils/config.template
> :car: Simple PulseAudio driver :smile:

- include/array.h
- src/emit/emit.c
- src/vm/vm_code.c
> :art: Put free_array_info where it belongs

- include/type.h
- src/emit/emit.c
- src/lib/array.c
- src/lib/opfunc.c
- src/parse/scan1.c
- src/parse/scan2.c
- src/parse/template.c
- src/parse/type_decl.c
- tests/error/arg_prim_ref.gw
- tests/error/function_ret_ref_prim.gw
- tests/error/new_prim.gw
- tests/error/prim_ref.gw
- tests/error/ptr_ref_prim.gw
> :art: Centralize prim_ref

- include/compile.h
- include/env.h
- include/object.h
- include/value.h
- include/vm.h
- src/gwion.c
- src/main.c
- src/oo/env.c
- src/oo/nspc.c
- src/oo/value.c
- src/parse/check.c
- src/parse/scan0.c
- src/parse/scan1.c
- src/parse/scan2.c
- src/vm/vm.c
Towards reentrant goal.
Next is Symbol table
> Remove global vm

- .travis.yml
- include/opcode.h
- include/type.h
- opcode.txt
- src/emit/emit.c
- src/lib/array.c
- src/lib/complex.c
- src/lib/func.c
- src/lib/import.c
- src/lib/instr.c
- src/lib/opfunc.c
- src/lib/vararg.c
- src/oo/type.c
- src/parse/check.c
- src/parse/func.c
- src/parse/operator.c
- src/parse/scan0.c
- src/parse/scan1.c
- src/parse/scan2.c
- src/parse/scanx.c
- src/parse/template.c
- src/parse/type_decl.c
- src/vm/vm.c
- tests/import/global_var.c
- tests/import/static_string.c
- tests/sh/plugin.sh
> Fptr fixes, macros and other improvments.

- include/instr.h
- include/vm.h
- src/emit/emit.c
- src/vm/vm.c
- src/vm/vm_code.c
Use encoded bytecode.
This give a nice speedup ( over one second on fib(40)) :smile:
> :cra: Encode bytecode : smile

- README.md
> :book: Fix README links [skip ci]

- README.md
Add steps for users to write their first program. 
Suggestions welcome.
> :book: Update README to add instructions to execute Hello World Program

- src/parse/scan0.c
> :art: Make scan0_section use similar style as scan<1/2>_section

- .github/workflows/cancel.yml
This should solve #187 "Newer workflows should cancel older ones."
> :wrench: Add Action to Cancel previous Workflows, if newer has been added

- scripts/test.sh
fixed issue #196 async mode,
changed -lt -> -gt
> 🐛 Fix async mode in tests #196

- README.md
> :book: Add Installation instructions

- include/tmp_resolve.h
- src/parse/check.c
- src/parse/func_resolve_tmpl.c
> :art: Move find_template_match and helping fns to new file

- .gitmodules
@fennecdjay I'm still working to understand how git submodules work, but I'm pretty sure we want to do this; a last bit of housekeeping from moving the repos.
> Update .gitmodules file to pull from new subproject locations

- src/parse/func_resolve_tmpl.c
Creates a new function fptr_match, for the ptr case. Created a struct for passing parameters to the function.
Partially fixes #204
> :art: Split _find_template_match (1/2)

- include/env/func.h
- src/lib/array.c
- src/parse/check.c
- src/parse/func_resolve_tmpl.c
@Pranav2612000, this is the pull-request I'd like you to review.
Along with being more respectful of the coding style, it solves a possible memory leak problem and improves perfomance.
The only thing left, IMHO is the public function, whose logic might be improved.
> Clean resolve tmpl

- README.md
Added a few hints that helped me install Gwion succesfully.
Thank you @fennecdjay for your guidance on Discord.
> docs: added a few hints for getting started

- highlighters/gwion.kak
Add a syntax highlighting description for the Kakoune editor.
> Add syntax highlighting for Kakoune

- highlighters/gwion.kak
> Add dur type to Kakoune highlighter
